In [ ]:
from google.colab import drive
drive.mount('/content/drive')

dataset_dir = "/content/drive/MyDrive/Dataset/train"


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size = (128, 128)
batch_size = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,

    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.7, 1.3]
)


train_data = datagen.flow_from_directory(
    dataset_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode="categorical",
    subset="training",
    shuffle=True
)

val_data = datagen.flow_from_directory(
    dataset_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)


Found 1073 images belonging to 6 classes.
Found 267 images belonging to 6 classes.


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(train_data.num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 126, 126, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 61, 61, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 28, 28, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     3,211,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,305,414 (12.61 MB)

 Trainable params: 3,305,414 (12.61 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)


/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 272s 8s/step - accuracy: 0.5244 - loss: 1.3639 - val_accuracy: 0.6292 - val_loss: 1.1868
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 387ms/step - accuracy: 0.6159 - loss: 1.1556 - val_accuracy: 0.6105 - val_loss: 1.0846
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 384ms/step - accuracy: 0.6117 - loss: 1.1568 - val_accuracy: 0.6180 - val_loss: 1.1187
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 387ms/step - accuracy: 0.6439 - loss: 1.0501 - val_accuracy: 0.6030 - val_loss: 1.0924
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 390ms/step - accuracy: 0.6086 - loss: 1.1427 - val_accuracy: 0.6367 - val_loss: 1.0798
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 391ms/step - accuracy: 0.6322 - loss: 1.0925 - val_accuracy: 0.6030 - val_loss: 1.1186
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 395ms/step - accuracy: 0.6594 - loss: 1.0308 - val_accuracy: 0.6105 - val_loss: 1.0751
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 13s 392ms/step - accuracy: 0.6558 - loss: 1.0323 - val_accura

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model

model.save("/content/drive/MyDrive/skin_allergy_cnn.h5")

# Class names as detected from train_data
labels = list(train_data.class_indices.keys())
print("Class Labels:", labels)


Class Labels: ['Acne and Rosacea Photos', 'Cellulitis Impetigo and other Bacterial Infections', 'Eczema Photos', 'Exanthems and Drug Eruptions', 'Light Diseases and Disorders of Pigmentation', 'Systemic Disease']


In [ ]:
from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/skin_allergy_cnn.h5")
print("Model loaded successfully")


Model loaded successfully


In [ ]:
#existing class labels
labels = list(train_data.class_indices.keys())
print("Class Labels:", labels)


Class Labels: ['Acne and Rosacea Photos', 'Cellulitis Impetigo and other Bacterial Infections', 'Eczema Photos', 'Exanthems and Drug Eruptions', 'Light Diseases and Disorders of Pigmentation', 'Systemic Disease']


In [ ]:
#prediction function
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array

def predict_skin_allergy(image_path):
    img = load_img(image_path, target_size=(128, 128))
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)

    predicted_index = np.argmax(prediction)
    predicted_label = labels[predicted_index]
    confidence = float(np.max(prediction))

    print("Predicted Class:", predicted_label)
    print("Confidence Score:", confidence)

    return predicted_label


In [ ]:
image_path = "/content/drive/MyDrive/Dataset/test/NS.jpeg"
predict_skin_allergy(image_path)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 724ms/step
Predicted Class: Acne and Rosacea Photos
Confidence Score: 0.4290010631084442


'Acne and Rosacea Photos'

In [ ]:
image_path = "/content/drive/MyDrive/Dataset/test/FSPA.jpeg"
predict_skin_allergy(image_path)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Predicted Class: Light Diseases and Disorders of Pigmentation
Confidence Score: 0.6186220645904541


'Light Diseases and Disorders of Pigmentation'

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Get true labels
true_labels = val_data.classes

# Predict probabilities
pred_probs = model.predict(val_data)

# Convert probabilities → predicted class index
pred_labels = np.argmax(pred_probs, axis=1)

# Get class names
class_names = list(train_data.class_indices.keys())

print("Class Names:", class_names)


9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 278ms/step
Class Names: ['Acne and Rosacea Photos', 'Cellulitis Impetigo and other Bacterial Infections', 'Eczema Photos', 'Exanthems and Drug Eruptions', 'Light Diseases and Disorders of Pigmentation', 'Systemic Disease']


In [ ]:
# CONFUSION MATRIX
cm = confusion_matrix(true_labels, pred_labels)
print("Confusion Matrix:\n")
print(cm)

# CLASSIFICATION REPORT
cr = classification_report(true_labels, pred_labels, target_names=class_names)
print("\nClassification Report:\n")
print(cr)


Confusion Matrix:

[[143   0   0   0  25   0]
 [ 12   0   0   0   1   0]
 [  5   0   0   0   2   0]
 [  2   0   0   0   2   0]
 [ 43   0   0   0  16   0]
 [ 16   0   0   0   0   0]]

Classification Report:

                                                    precision    recall  f1-score   support

                           Acne and Rosacea Photos       0.65      0.85      0.74       168
Cellulitis Impetigo and other Bacterial Infections       0.00      0.00      0.00        13
                                     Eczema Photos       0.00      0.00      0.00         7
                      Exanthems and Drug Eruptions       0.00      0.00      0.00         4
      Light Diseases and Disorders of Pigmentation       0.35      0.27      0.30        59
                                  Systemic Disease       0.00      0.00      0.00        16

                                          accuracy                           0.60       267
                                         macro avg     

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
